### ISSUE TITLE
What model?

### ISSUE THREAD

**Issue by dcmeglio** [sh00t2kill/petoneer_custom_component#13]
I stumbled on your repository. I am looking for a smart cat water fountain, what model does this integration work with and where were you able to find it?

**Comment by sh00t2kill** [comment]
The one i have is called a "Petoneer Fresco Pro"

https://www.petoneer.com/fountain

In theory the integration should work with anything else that uses the fresco pro app, but AFAIK this is the only device that uses it.

**Comment by dcmeglio** [comment]
Thanks, but darn looks like it's not available in the US :(
