### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by freestyler164** [sh00t2kill/petoneer_custom_component#14]
Thank you for creating this component. 

I recently got a new Fresco pro and was trying to use this custom component. I seem to get a auth error with integeration

`Error setting up entry Petoneer Revogi for revogi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/revogi/__init__.py", line 43, in async_setup_entry
    await pet.auth(username, password)
  File "/config/custom_components/revogi/petoneer.py", line 82, in auth
    if (json_resp['data']['accessToken']):
KeyError: 'accessToken'
`

I tried using the API https://as.revogi.net/app/user/101 directly and seem to get an uname and password error too. 

The login to the Mobile App seems ok so I guess I got the uname and pwd right :)

**Comment by sh00t2kill** [comment]
Are you using the Fresco Pro app, or one of the other "petoneer" apps?

There seems to be a few different ones!

**Comment by freestyler164** [comment]
Ah right! I am using the petoneer app. It was mentioned in their doco. 

I tried setting up with the Fresco App but cant seem to set it up through that one.

**Comment by sh00t2kill** [comment]
Unfortunately they have a number of different products. Different ones use different apps. Its all pretty confusing.

The petoneer app is tuya based. Theres a forum thread RE using localtuya.
