### ISSUE TITLE
Is there any manual for setting up this addon?

### ISSUE THREAD

**Issue by romanad** [sh00t2kill/petoneer_custom_component#15]
Hi!
The readme is empty and there's no explanation about configuration.
Petoneer has different accounts for several phone apps that support this fountain, no info what account to use.
What type of serial should use and where to find it and how to configure the addon. 
Thanx in advance.

**Comment by dwheaton-paloit** [comment]
The app I use for my fountain is called Freso Pro.
It uses a revogi back end. Any app called Petoneer is Tuya based, and there has been some success getting those working with localtuya.

Ill have to dig as to how i found the serial. If I cant find it i will make a change so that its no longer required and will just grab all devices it finds which I have been wanting to do for a little while.

**Comment by sh00t2kill** [comment]
The app I use for my fountain is called Freso Pro.
It uses a revogi back end. Any app called Petoneer is Tuya based, and there has been some success getting those working with localtuya.

The serial can be found in the app -- under Settings -> About.

I have wanted to remove that requirement for a little while and automatically grab devices, but havent got around to it

**Comment by ond000** [comment]
And which number is serial number? we have DevId, PID and UUID? I have error on setup:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/revogi/__init__.py", line 43, in async_setup_entry
    await pet.auth(username, password)
  File "/config/custom_components/revogi/petoneer.py", line 82, in auth
    if (json_resp['data']['accessToken']):
KeyError: 'accessToken'

I'm not sure what this error means...

Thanks for help.

**Comment by sh00t2kill** [comment]
I don't have any of those values on the about page.  Maybe you are using a different app?

I see S/N , SAK, mac and ip address.

The error means unable to login

**Comment by romanad** [comment]
I have Petoneer Fresco Mini Pro, maybe this addon doesn't support that specific model

**Comment by sh00t2kill** [comment]
Are you using the Fresco Pro app, or one of the flavours of petoneer apps?

**Comment by romanad** [comment]
> Are you using the Fresco Pro app, or one of the flavours of petoneer apps?

App name is "Petoneer"

**Comment by sh00t2kill** [comment]
Unfortunately that's the tuya based one.

**Comment by romanad** [comment]
For some reason I wasn't able to connect device to that app. Looks like this app for regular Fresco Pro - not mini variant.

**Comment by sh00t2kill** [comment]
It looks that way yeah. There are 3-4 different Petoneer a pps. When i first got my fountain it took me a while to find the right one!

It seems all other apps are tuya based. There is a thread on the HA community forum where people have had some luck getting it paired using the smart life app, and using localtuya.

Sorry this didnt work for you.
