### ISSUE TITLE
Petoneer Fresco Ultra Support

### ISSUE THREAD

**Issue by DimChik2903** [sh00t2kill/petoneer_custom_component#19]
Hello! I have a fountain Petoneer Fresco Ultra. It works with the Petoneer application, not with the Petoneer Pro application. Does this component support it? Thank you in advance!

**Comment by sh00t2kill** [comment]
I don't believe so.
The petoneer app is tuya based.

Some users have had luck with local tuya but then you can't use the native app.

**Comment by DimChik2903** [comment]
It's a pity, thank you!
