### ISSUE TITLE
user name or password wrong

### ISSUE THREAD

**Issue by acheglakov** [sh00t2kill/petoneer_custom_component#23]
Hello!

Thank you for this app! I got an error:

`2024-02-05 21:44:59.391 DEBUG (MainThread) [custom_components.revogi.petoneer] Petoneer Python API`
`2024-02-05 21:44:59.391 DEBUG (MainThread) [custom_components.revogi.petoneer] Authenticating to https://as.revogi.net/app as aXXXXXXXXX@yandex.ru...`
`2024-02-05 21:45:00.776 DEBUG (MainThread) [custom_components.revogi.petoneer] {'data': {'message': 'nothing'}, 'code': 418, 'response': 101, 'msg': 'user name or password wrong'}`

But my password is correct. It contains only letters and numbers. Tried to change country and timezone but without no luck. Could you please help me?

**Comment by sh00t2kill** [comment]
Hi.
Which app do you have your fountain setup with ?
This adon only works with the "Fresco Pro" app. If you are using a tuya variant (eg the smart life or tuya apps) or the Petoneer app (which is also Tuya), it wont work unfortunately.

**Comment by acheglakov** [comment]
Hello! Thank you for your answer! I am using Petoneer app v 2.9.7. I tried to use Fresco Pro, but it could not find my Fresco Mini Pro fountain.
